### ISSUE TITLE
Non-Labeled Nest devices need better unique name then "Nest[device-id]"

### ISSUE THREAD

**Issue by KraigM** [KraigM/homebridge-nest#10]
If a label was not specified for a Nest device, it was defaulted to "Nest" due to name conflicts (which I believed caused issues in HomeBridge) it was later changed to default to "Nest[device-id]".  Which is nasty looking and (depending on the app) can't be changed.

Instead we need a more intelligent solution to solve name issue. My current thought on order of picking the name is (using first found):

1. The Label like it looks for now

2. If the Room is specified and unique, Room + "Nest" (i.e. "Hallway Nest")

3. If only one device, then just "Nest"

4. If only one in the house, then "[Home Name] Nest"

5. Fall back to "Nest [device-id]"

**Comment by jdwhite** [comment]
Posted this on another thread, but I did add a label "Nest" to my "Living Room" nest, so now it displays as "Living Room (Nest)".  Siri now just says "Nest" instead of rattling off the deviceID, which is a huge improvement.

**Comment by vogelboy** [comment]
jd- Where did you add the label/what did you change to do this?

**Comment by jdwhite** [comment]
I used the iOS mobile app. Starting from the main screen where you see the nest in the middle and the Home/Away status above it:
* tap the gear icon in the upper right corner
* select the appropriate thermostat in the *thermostats* section
* tap the top entry, *Where*
* tap *Label* and enter a label.

**Comment by KraigM** [comment]
Should be fixed under #11 (coming very soon) but I might be able to be convinced to fix the legacy if necessary :-)

**Comment by vogelboy** [comment]
Kraig- Awesome :)
jd- Your solution worled int he mean time, all I had to do was delete my homekit data from my iOS device and re-add homebridge. My Nest now comes up as "Nest". Thanks!

**Comment by KraigM** [comment]
The new version that uses the official Nest API has been released to npm (1.0.0) and it will solve the name issue as well as many others.  The old unofficial API is still supported by version 1.0.0, but this issue will not be fixed with the old unofficial api.  For more information, see the [main page](https://github.com/KraigM/homebridge-nest/).
