### ISSUE TITLE
Installation documentation may  be unclear?

### ISSUE THREAD

**Issue by rajid** [KraigM/homebridge-nest#101]
I recently installed this plugin and followed the documentation.  My situation was possibly unusual in that I already had a Nest Developer account?  When I logged in to Nest, I didn't see a "Step 2", but instead went to the "Go to Products" step.  At that point, I found that I couldn't register a product named "Homebridge" because one already exists.  I had to list mine as "homebridge-raj" instead.  Everything else in the instructions worked fine.  So, these are relatively minor points, but I was thinking the documentation should probably take them into account in order to not confuse people.

That's all!

**Comment by dscottfrey** [comment]
The API setup seems to have radically changed and I cannot seem to to follow the instructions at all.

**Comment by JJJ** [comment]
I just set this up, and didn't have any issues with the instructions as they are in the various readme's.

**Comment by rajid** [comment]
I just had some issues regarding setting up the Nest developer account, but it wasn't that big of a deal to figure it out and it's been so long now that I don't remember the issue or the workaround. I'd vote to close this bug.
