### ISSUE TITLE
Issues with install. 

### ISSUE THREAD

**Issue by quicksilverusu** [KraigM/homebridge-nest#105]
I don’t think i’m quite understanding steps 10-15 right.
Questions I have:

1. Do you mean that we need to create our own config.json file in /.homebridge?
2. When you say not to include the token the first time we run ‘homebridge’, do you mean that we need to delete out the c.5ABsTpo88k5yfNIxZlh…’ example and just leave it as “token” : “ “,?
3. For whatever reason, I did manage to get it to work one time, but it looks like that's because it fell back to using the legacy API.
4. Also, how does homebridge continue to run? The process seems to stay open. Once I close the terminal or control+c, homebridge will shutdown. (ex., Got SIGINT, shutting down Homebridge…)

**Comment by petaren** [comment]
For step 4:
Write `homebridge&` and that will start homebridge *"in the background"*.

**Comment by quicksilverusu** [comment]
Closing this. Found a solution running homebridge on boot through systemd https://github.com/nfarina/homebridge/wiki/Running-HomeBridge-on-a-Raspberry-Pi
