### ISSUE TITLE
Fahrenheit or Celsius

### ISSUE THREAD

**Issue by KevinOlive** [KraigM/homebridge-nest#12]
Either I'm the only one using Fahrenheit or I'm missing something—of course, the latter seems more likely. The display clearly shows that the units should be fahrenheit but it displays Celsius.  I should add that I'm using MyTouchHome. I am using the master branch 

![img_0161](https://cloud.githubusercontent.com/assets/16341956/11881763/66583d68-a4ce-11e5-8b32-530ccdb710af.png)

**Comment by KraigM** [comment]
It's a problem my that app (not the first to report to me).  That app did not implement HomeKit correctly.  Try [Insteon+](https://itunes.apple.com/us/app/insteon+/id919270334?mt=8) or [Elgato Eve](https://itunes.apple.com/us/app/elgato-eve/id917695792?mt=8)

**Comment by KraigM** [comment]
I prefer Insteon+ most of the time (nice interface and fulfills almost all of the HomeKit api properly). 

Elgato Eve kind of has a bobo interface but I have yet to find anything that it didn’t support

For instance, HomeBridge-Nest support setting Home/Away status from the Nest device. Insteon+ shows it but doesn’t label it and doesn’t let you control it.  But Elgato Eve displays it correctly and lets you control it

**Comment by KevinOlive** [comment]
i didn't realize the elgato eve app was available without the device. I've just set all of this up last night. Eve does give the correct readings.  
Thanks.

**Comment by KraigM** [comment]
Yep. Same with Insteon+
