### ISSUE TITLE
Two factor auth options?

### ISSUE THREAD

**Issue by jaytay79** [KraigM/homebridge-nest#121]
As per their [recent news](https://nest.com/blog/2017/03/07/extra-security-for-your-nest-account/) Nest have now enabled 2 factor authentication. However if this option is enabled on your account then the plugin will not load which prevents homebridge from fully starting. I thought I would open this issue to a) make people aware and b) see if there any options to get the plugin working with 2 factor auth enabled.

**Comment by DJay1** [comment]
Thx @jaytay79 
I just can give the feedback that my three Nest Protect still up in Homebridge. Everything is fine here.
2 factor auth on since the release a couple of days and Homebridge reboot a couple of times a day.

**Comment by jaytay79** [comment]
@DJay1 I tried it a few times and it hung every time but started first time as soon as I'd disabled two factor :( I'll re-enable it and try it again now....

**Comment by jaytay79** [comment]
OK, have since tried again and it's working fine so must have been a one-off glitch.
