### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by idumzaes** [KraigM/homebridge-nest#129]
whenever I try to install this plugin or others remotely related to this, I get an error 1 on npm.
I am able to install any other plugin just fine, just not Nest.
I attempted clearing out the cache and didn't fix.
Same issue on two different Macs and a rPi.

heres the error.

```
$ sudo npm install -g --unsafe-perm https://github.com/KraigM/homebridge-nest
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/KraigM/homebridge-nest.git /Users/admin/.npm/_cacache/tmp/git-clone-d9e3dfc7
npm ERR! /Users/admin/.npm/_cacache/tmp/git-clone-d9e3dfc7/.git: Permission denied
```

**Comment by roe1974** [comment]
what was the solution ?

**Comment by idumzaes** [comment]
I asked a friend to send me the homebridge-nest folder from his set up. I copied into place, restarted and it worked as expected.

**Comment by roe1974** [comment]
ok, ...but i have nobody to sent me the folder 😞


________________________________
Von: idumzaes <notifications@github.com>
Gesendet: Freitag, 25. August 2017 14:52
An: KraigM/homebridge-nest
Cc: roe1974; Comment
Betreff: Re: [KraigM/homebridge-nest] Unable to install (#129)


I asked a friend to send me the homebridge-nest folder from his set up. I copied into place, restarted and it worked as expected.

**Comment by idumzaes** [comment]
Do you perhaps have a previous backup?

**Comment by roe1974** [comment]
no ... its my initial installation ....

*** Mit meinem iPhone gesendet ***

Am 27.08.2017 um 11:41 schrieb idumzaes <notifications@github.com<mailto:notifications@github.com>>:


Do you perhaps have a previous backup?

**Comment by roe1974** [comment]
can you send me the necessary fiels ?


Richard


________________________________
Von: idumzaes <notifications@github.com>
Gesendet: Sonntag, 27. August 2017 11:41
An: KraigM/homebridge-nest
Cc: roe1974; Comment
Betreff: Re: [KraigM/homebridge-nest] Unable to install (#129)


Do you perhaps have a previous backup?

**Comment by roe1974** [comment]
can you send me the files ?
Richard
