### ISSUE TITLE
Nest Outdoor Camera not editable

### ISSUE THREAD

**Issue by JJJ** [KraigM/homebridge-nest#134]
iOS 11 beta 6
tvOS 11 latest beta
Raspberry pi 3

Everything else is great, but 1 Camera is totally uneditable. Any guesses how to fix this?

![44100edd-b3f6-42f5-ab10-849e540d6842](https://user-images.githubusercontent.com/88951/29502559-932c6bc4-85f6-11e7-8af6-31f5b13c9b1f.png)

**Comment by djfatal** [comment]
This problem eventually went away after iOS 11 was released but as of 11.1 beta 2 it has returned.

**Comment by JJJ** [comment]
> This problem eventually went away after iOS 11 was released but as of 11.1 beta 2 it has returned.

It's been OK with me on both 11 and the most recent 11.1 beta releases.

I'm comfortable marking this as resolved, at least for now.
