### ISSUE TITLE
unable to install (NPM 5.3.0, Nodejs 8.4.0) ?!?!?

### ISSUE THREAD

**Issue by roe1974** [KraigM/homebridge-nest#137]
i am unable to install NEST Plugin

sudo npm install -g homebridge-nest
result:
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/kraigm/unofficial_nodejs_nest.git /root/.npm/_cacache/tmp/git-clone-8f64a85a
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-8f64a85a': Permission denied
npm ERR!

what's wrong !??!?

Richard

**Comment by Spown** [comment]
So, what was wrong? I have the same aggravating issue.

**Comment by rolfen** [comment]
It looks like a bug in npm.
try to run the clone command directly
```
sudo /usr/bin/git clone -q https://github.com/kraigm/unofficial_nodejs_nest.git /root/.npm/_cacache/tmp/git-clone-8f64a85a
```
If it works then most probably node is not doing sudo on that command hence it is failing.
Maybe do `sudo su` then try install, or change the permissions of `/root/.npm/_cacache/tmp/` to 777.
