### ISSUE TITLE
Nest Thermostat Auto Mode Settings

### ISSUE THREAD

**Issue by jeffzacharias** [KraigM/homebridge-nest#14]
I have been testing this with the new Nest API and it has been working OK. My main issue is that I have 3 Nest thermostats and they are all set in Auto changeover mode.  That means there are 2 temperature settings for each thermostat, low and high. This only shows the current temperature and only allows me to adjust one of the temperature settings.  I'm not sure how it picks which temperature setting, low or high, to adjust. I would like to be able to see the current temperature and to be able to adjust both the low and high temperature settings.

**Comment by KraigM** [comment]
HomeKit was not designed for this unfortunately.  It used to not allow you to change it at all but I added some code that allows you to change whatever temperature is closer to the current temperature.  In other words, if the range you set is 67 - 72 and it is currently 75, it will show and allow you to adjust the high temp, but if it was 68, it will show and allow you to adjust the low temp.

**Comment by bheung** [comment]
The optional characteristics `Characteristic.HeatingThresholdTemperature` and `Characteristic.CoolingThresholdTemperature` exist and probably can be exposed to correspond with the high and low temperature settings. The 3rd party apps I tried didn’t know what to do with them but HMCatalog sample code does show those fields.

**Comment by jeffzacharias** [comment]
KraigM - Thanks for the reply. Now I understand how it is working. 
bheung - I had started to look at this but I hadn't seen these characteristics.  I will definitely take a look at this next week.

**Comment by KraigM** [comment]
@bheung Prob with that is I don't think we can change those.  We might however be able to incorporate them to display the other temp or at least let them be known (maybe). 

For now Im going to close this.  Another item can be created to investigate alternatives if wanted

**Comment by jfanok** [comment]
It looks like this is possible now with the new "heater cooler" service 

http://imgur.com/a/SB0lI

https://m.imgur.com/HiRVQYd?r
