### ISSUE TITLE
Siri only tell the temperature in F

### ISSUE THREAD

**Issue by toshibochan** [KraigM/homebridge-nest#162]

**Comment by toshibochan** [comment]
My nest thermostat is set to C and home app is set to C but Siri only tell me in F. But I have temperature sensor in the raspberry pi and give me correct temperature in C! Any one have F and C problem?

**Comment by chrisjshull** [comment]
C vs F is an iOS-level setting (oddly). Go to Settings and search for "Units".

**Comment by toshibochan** [comment]
I did change in iOS setting to region to United States and units to Celsius. All the other 3 temperature sensor in my raspberry pis Siri give me temperature in Celsius but on nest Siri only give me temperature in  F.

**Comment by toshibochan** [comment]
I don’t know what happens but today I ask Siri again and now she give me temperature in Celsius

**Comment by toshibochan** [comment]
I’m clouding thanks
