### ISSUE TITLE
Problem reading your config.json file

### ISSUE THREAD

**Issue by maartenvant** [KraigM/homebridge-nest#163]
I followed all the steps but the config.json file after validating it on https://jsonlint.com

Error: Parse error on line 20:
...code": "MQUUDFGP",	}]}
----------------------^
Expecting 'STRING', got '}'

The code MQUUDFGP I got after opening the Authorization URL of my product created in Nest developer platform.

**Comment by chrisjshull** [comment]
Try removing the comma before the }

**Comment by maartenvant** [comment]
Unfortunately doesn't solve it. I attached my config json

[config.txt](https://github.com/KraigM/homebridge-nest/files/1671422/config.txt)

**Comment by maartenvant** [comment]
Solved it :)
