### ISSUE TITLE
Crash: Error: getaddrinfo ENOTFOUND 

### ISSUE THREAD

**Issue by ptigoe** [KraigM/homebridge-nest#17]
Running homebridge / homebridge-nest on Mac OS X Server El Cap. Runs fine for a few hours then crashes as shown:

Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND czfe04-front01-iad01.transport.home.nest.com czfe04-front01-iad01.transport.home.nest.com:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

**Comment by KraigM** [comment]
Which version are you using?  The currently released version or the prerelease version?

**Comment by ptigoe** [comment]
I think the currently released version? I installed as follows:

sudo npm install -g homebridge-nest 

which returned:

/usr/local/lib
└─┬ homebridge-nest@0.1.1 
  ├── inherits@2.0.1 
  └── unofficial-nest-api@0.1.4  (git+https://github.com/kraigm/unofficial_nodejs_nest.git#3cbd337adc32fab3b481659b38d86f9fcd6a9c02)

**Comment by KraigM** [comment]
Yes that is the currently released version which is known to have issues as it uses an unofficial nest api.  If you want to try out the new version (which uses an official API) see #11. I strongly recommend it, its backwards compatible, and you can always go back by running `sudo npm install -g homebridge-nest` again

**Comment by ptigoe** [comment]
OK. I went through all of the steps in the https://github.com/KraigM/homebridge-nest/blob/develop/README.md referenced in #11 for the official API and it seems to be working so far. I'll followup if I see any issues. Thanks for making this!

**Comment by KraigM** [comment]
That version was just officially released to npm (as version 1.0.0).  If this still happens with the new version, just let me know :smile:
