### ISSUE TITLE
Opinion for stop ecomode

### ISSUE THREAD

**Issue by toshibochan** [KraigM/homebridge-nest#190]
Ecomode is messing my homebridge tuning on my AC
Please make true o false to use ecomode and home occupied in the config.json

**Comment by toshibochan** [comment]
Sorry not opinion is option

**Comment by chrisjshull** [comment]
This is no longer the canonical repo for this module. Please file a bug here: https://github.com/chrisjshull/homebridge-nest/issues/new/choose
