### ISSUE TITLE
Away status

### ISSUE THREAD

**Issue by luc-ass** [KraigM/homebridge-nest#2]
Hey, have you been able to represent "Away" in some way?

**Comment by pedroserano** [comment]
Speaking of, I was noodling around with adding an OccupancySensor service to the homebridge-nest code that just updates the sensor's characteristic OccupancyDetected with the Nest home or away status. When I add the OccupancySensor service to a hypothetical thermostat in HomeKit Accessory Simulator and add it to homekit on my phone it works. When I add the same OccupancySensor service to the homebridge-nest code, homebridge runs fine, but once I try to add Homebridge on my phone to homekit I get an error saying "out of order the requested device does not conform to homekit specifications" so I'm stuck.

**Comment by luc-ass** [comment]
Perhaps you can add it as a separate device (like nest-occupancy). That might be not as convenient but will still serve the purpose. I think that thermostat accessories cannot have an occupancy state. Let me know how it went.

**Comment by KraigM** [comment]
From the looks of it, we can just add it as a separate characteristic to the Thermostat Service.  I messed around with the HomeKit Accessory Simulator and it didn't seem to matter to the Eve app whether it was a new characteristic or a new service (Insteon+ displays it but doesn't allow you to control it).  We can treat it as a separate device but personally I'm not a fan of that given that HomeKit was designed with this exact situation in mind.  Eve also accepted a custom characteristic so we can actually label it something like "Home", "Home Status", or "Is Home".

**Comment by leoneleone** [comment]
I do not have a Nest thermostat (it isn't compatible with my heating and AC system), but I do have a few Nest Cams around the house. While I can add my Nest account via Homebridge, it obviously doesn't show my Nest Cams as devices in HomeKit - I understand IP Cameras aren't supported yet (or perhaps they could be as part of a "security system" or "motion sensor" device type?).
What I would definitely want to have is a Nest account Home/Away or Home On/Off toggle which will affect my Nest Cams and set them to either Home or Away.
Such a switch/toggle can then be added to my HomeKit "I'm Home" and "I'm Leaving" Scenes to turn on and turn off my Nest Cams as needed.

Is this something that would be possible?
Are there any Plans to support Nest Cam as part of the home bridge-nest plugin?

**Comment by zb0th** [comment]
Just pushed a PR that adds support for the Away status 

https://github.com/KraigM/homebridge-nest/pull/5

**Comment by KraigM** [comment]
#5 has been merged and released in version 0.1.0

**Comment by KraigM** [comment]
Thanks @zb0th

**Comment by zb0th** [comment]
:bow:

**Comment by chrisgrande** [comment]
I see that it appears as a custom toggle... I'm trying to figure out how to get that to say Away so that it can then be accessed via Siri.

**Comment by KraigM** [comment]
Not sure it can at the moment but haven't tried. @zb0th ?

**Comment by zb0th** [comment]
It is supposed to show as Away, but it seems most apps do not read  the metadata of custom characteristics. In Eve it shoes as Away, but in every other app I've tried it shows as N/A.

What I did to get it working was to create a scene named "Any name you want"  and then setup the scene to set the toggle to the value you want. Then you can trigger the scene using Siri :)

**Comment by leoneleone** [comment]
No need to set the toggle as a scene. It can be put in a "Service Group" named Away.

**Comment by zb0th** [comment]
Cool!
