### ISSUE TITLE
Auto-Away should be treated as away per API documentation

### ISSUE THREAD

**Issue by KraigM** [KraigM/homebridge-nest#21]
After further investigation, **auto-away** means _"Nest has determined algorithmically that no one is home. Currently there is no way to vote on entering this state via the Nest cloud API. Clients are expected to use explicit controls or actions that will set away directly rather than algorithmically."_, where as **home** is used for both auto and manual _"There is someone in the house, either because Nest has high confidence from motion sensor data, or the user has explicitly set the structure to home via a Nest app, your product, or via ETA."_

https://developer.nest.com/documentation/cloud/how-to-structures-object

**Comment by hnryjms** [comment]
I'll take this on.

**Comment by KraigM** [comment]
I just pushed the change.  Releasing it now

**Comment by KraigM** [comment]
@hnryjms But I would happily accept your help in the future :smile:

**Comment by KraigM** [comment]
Released in version 1.0.1
