### ISSUE TITLE
Attempts to change Nest settings no longer work (Firebase warns as failure: blocked) 

### ISSUE THREAD

**Issue by peterwooley** [KraigM/homebridge-nest#24]
I'm getting a Firebase Warning when attempting to change any Nest setting through Insteon+ as well MyTouchHome. For example, when setting the temperature, I get:

```
Setting target temperature for Nest to: 68
Target temperature for Nest is: 68 F
FIREBASE WARNING: set at /devices/thermostats/Dsk9FNKDY1nqZ2y7MVC3ztxc6zC1sr1x/target_temperature_f failed: blocked
Target temperature for Nest is: 67 F
```

I just got Homebridge set up along with homebridge-nest and was _delighted_ to change settings through both the MyTouchHome and Insteon+ apps. I adjusted settings for a few minutes, getting an understanding for how both apps render the information. When I attempted to change the target temperature in MyTouchHome, I got errors (likely because of the thresholding of Cool+Heat mode), but changing the other options (Mode and Away) worked in both apps.

Then, after 5 minutes of fooling around, I started getting the above error no matter what I changed. I've restarted `homebridge`, which didn't fix the issue. I then tried out the nuclear option: deleted the Homebridge accessory, changed my `username` in `config.json`, re-created my `token`, and re-registered the accessory in Insteon+. Still, no luck.

As I'm a n00b, I'm sorry if I missed an already documented fix for this. I searched for the error in repo, but couldn't find it and I'm not familiar enough with Firebase to know why it would return `blocked`.

Last thing of interest: Even after I tried the nuclear option, the errors shown in the log refer to the same `/device/thermostats/<id>`. For example, when I tried to set the mode before I removed and re-added, I got this error:
```
Setting target heating cooling for Nest to: cool
Target heating for Nest is: Cooling
FIREBASE WARNING: set at /devices/thermostats/Dsk9FNKDY1nqZ2y7MVC3ztxc6zC1sr1x/hvac_mode failed: blocked
```

In both errors, the thermostat ID is `Dsk9FNKDY1nqZ2y7MVC3ztxc6zC1sr1x`. I assumed it would change once I re-created my `token`.

Are you aware of anything I can do to get past these errors?

**Comment by spmcewen** [comment]
I've noticed some strange behavior since setting up Homebridge and I don't think it's working reliably all the time. I've noticed the same warnings.  

I'm using the Home app (but Lutron also shows the same thing), and my temperature is currently being reported incorrectly. I thought it had to do with the Nest being in auto away mode but I just ended that and the temp is still wrong.  Sometimes my Siri or HomeKit Scene commands simply fail, then work again the 2nd or 3rd time trying.

I really just wish I had a Ecobee that natively works with HomeKit.

**Comment by KraigM** [comment]
The "blocked" comes when you make too many changes within some given period.  Im not sure what that number/period is but once you hit it, you are blocked until the time period is up.

**Comment by pilot76103** [comment]
I have also started getting this error now as well. Will let it sit overnight and re-test tomorrow.

**Comment by KraigM** [comment]
Well hopefully this helped.  At some point we will switch to the Nest Weave api which hopefully won't be as restricted and hopefully will be a little simpler to setup/register.

**Comment by offdwall** [comment]
I just set up homebridge with a Nest thermostat and am having the same issue. All worked, did a bunch of temp changes to the nest then it stopped working with the FIREBASE errors. 

What is the timeout period?

**Comment by exhaze** [comment]
https://developers.nest.com/documentation/cloud/data-rate-limits

Nest doesn't specify what the rate limit is, but looks like they are per hour, so you'd have to wait an hour at most for the reset.

It'd be great if the homebridge nest API was aware of this and implemented some handling for this. I see two approaches:

1). implement debouncing - I suspect a lot of the rate limiting is a result of an overly eager UI sending incremental target temperature commands as the user is dragging the temperature from the current setting to their target setting. It's hard to go and police every single consumer of `homebridge-nest`, so it makes more sense to implement it in here IMO

2). fall back to the legacy API (this is what the native mobile Nest app uses, right? I don't think it's subject to the same rate limits).

**Comment by clintonb** [comment]
This issue should be combined with https://github.com/KraigM/homebridge-nest/issues/82.

**Comment by bansonln** [comment]
Having the same issue. What is strange is that one of my thermostats work fine but the other doesn't. I keep getting:

Target temperature for Downstairs Thermostat is: 75 F
FIREBASE WARNING: set at /devices/thermostats/mkeXm95OwexK4h6859XbK_Qu6UEV_fgf/target_temperature_high_f failed: blocked 

scratch that. They were working fine for about 5 mins. my downstairs stopped working, upstairs was working fine for a couple more minutes and then it stopped as well...
