### ISSUE TITLE
Nest all of a sudden started getting "TypeError"

### ISSUE THREAD

**Issue by EnigmaFx** [KraigM/homebridge-nest#26]
im not sure what happened everything was working perfect for weeks today all of a sudden i get this error http://d.pr/i/1bzQ2  

anyone know how to resolve this and/or what caused it?

**Comment by KraigM** [comment]
I posted a note on #slack but Nest is down right now.  So the cloud API fails and it falls back to the old api which times out.

**Comment by KraigM** [comment]
https://nest.com/support/#status

**Comment by EnigmaFx** [comment]
@KraigM oh ok nice :) thx for the update mate,  so im assuming we don't have to do anything its  just a waiting game until they are back up? correct?

**Comment by KraigM** [comment]
Currently posted status announcements for those just as a future note

```
Nest Service Issue

We’re experiencing a problem with the Nest web and mobile apps and are investigating the cause. We’ll have more details soon.
```

```
Nest Thermostat Issue

Some customers may be experiencing an issue with their Nest Thermostat becoming slow, unresponsive, or unable to turn on because the battery has drained. You should recharge and restart your thermostat following these steps.
01/09/2016 12:17
```

**Comment by KraigM** [comment]
@EnigmaFx Yes just a waiting game.  We need to handle this better (i.e. not stop home bridge from loading), but I doubt it will be down long enough to merit fixing it this second.  I just disabled my Nest on homebridge for now.

**Comment by EnigmaFx** [comment]
@KraigM http://d.pr/i/103k0  <---  should the nest service being down effect the entire hombridge? ( harmony and any other platforms/accessories as well? ) because i am also unable to get the harmony hub load/function as well?

**Comment by KraigM** [comment]
Read my last message

**Comment by EnigmaFx** [comment]
@KraigM sorry refreshed the page didnt see it NP thx mate
