### ISSUE TITLE
Nest plugin not stating correct temperature

### ISSUE THREAD

**Issue by JerGitHub** [KraigM/homebridge-nest#27]
So....I had everything working with the older version of the plugin (just user/pass). I just updated everything to the latest Nest Dev API version and it loads everything perfectly: 

homebridge to 0.2.15
homebridge-nest to 1.0.1
(and homebridge-liftmaster to 0.1.1 which is a different issue)

I deleted homekit data on my iPhone, deleted persist, rebooted but when I query one of my Nests as:

"What is the temperature in the Office?" Siri understands but gives me the target temp that the Nest is set to (67 F) Not the current temp it really is (73 F). I have 7 Nests and all of them give me the target temp and not the current actual temp in each room when I ask Siri what the temperature is for that room.

When initializing homebridge here is the info on the Office Nest:

Temperature unit for Office is: Fahrenheit
Current temperature for Office is: 73 F
Current humidity for Office is: 25%
Target temperature for Office is: 67 F
Target heating for Office is: Heating
Away for Office is: false

Asking Siri "What is the temperature in the Office?" (and all other rooms) worked perfectly with the old homebridge-nest plugin. Any ideas?

**Comment by KraigM** [comment]
As stated in the README

_Note: The name of the device will change as well. It matches the name displayed in the Nest app. In my case, I originally configured the Nest app so the the "Where" of my Nest was "Hallway" and I also added a label which was "Nest", so the display was "Hallway (Nest)". To fix the name to say "Nest", you can use the Nest app and blank out the "Label" and use the custom "Where" of "Nest". Anther option to fix the name is through HomeKit. HomeKit allows you to rename Accessories and Services, but it requires an app like Insteon+ that has the ability to change the name._

**Comment by JerGitHub** [comment]
OK - I should have stated that was already done. When I ask Siri "What temperature is the Office?" or "What temperature is the Office Nest?" it gives me the same response - the Target Temp and not the Current Temp.

**Comment by adamstephenson** [comment]
@JerGitHub try asking Siri "how warm is it in the Office" (or Office Nest) instead of what's the temperature [target temp]. That works for me in my home with one Nest. "How warm is it in __?" results in ambient temp, and "What's the temp___?") is the thermostat target setting.

**Comment by JerGitHub** [comment]
AH HA! That did it @adamstephenson! That's a little bit annoying especially since it worked with the older plugin but OK, I guess I can live with that. I wonder why it's different after the update to the latest?

**Comment by KraigM** [comment]
It should not work any diff.  Maybe homebridge or Apple changed something?  If you don't mind @JerGitHub, can you try removing new api configs (token, clientId, clientSecret, code) by either renaming them or copying them somewhere and deleting them.  Then see if it really did work before.  The legacy code remains unchanged but only gets used if the new api cannot be established.

**Comment by KraigM** [comment]
Ok I think I figured out the issue.  If you ask the temperature of a device then siri responds with target but if you ask the temperature of a room or zone then siri responds with the ambient temp determined from sensors or thermostats in that room or zone.

For me I call my nest _Nest_ and it is in the _Hallway_ room which is in the _Inside_ zone.  So if I ask _"What is the temperature of the Nest?"_ then Siri responds with the target temp, but if I ask _"What is the temperature inside?"_ then Siri responds with the ambient temp.

Try renaming your nest using one of the methods stated above.

**Comment by adamstephenson** [comment]
Kraig, great analysis and suggestion. I hadn't setup any zones yet and just did like yours. "What's the temperature inside?" works as described. 



On Sun, Jan 10, 2016 at 3:50 PM -0800, "KraigM" <notifications@github.com> wrote:












Ok I think I figured out the issue.  If you ask the temperature of a device then siri responds with target but if you ask the temperature of a room or zone then siri responds with the ambient temp determined from sensors or thermostats in that room or zone.



For me I call my nest Nest and it is in the Hallway room which is in the Inside zone.  So if I ask "What is the temperature of the Nest?" then Siri responds with the target temp, but if I ask "What is the temperature inside?" then Siri responds with the ambient temp.



Try renaming your nest using one of the methods stated above.

**Comment by JerGitHub** [comment]
OK - I don't have zones setup (never have) but I do have rooms. I kept the HomeKit Office Room name as "Office" but have changed the Accessory name to "Car" just to test it. It now gives me a range as you can see in the screenshot.

Thinking through this a bit more....the name of my Nests are all the same name as my HomeKit Room names but the Accessory Names are all different. For example here is a list of all my Nests upon Homebridge initialization:

Initializing platform accessory 'Office'...
Initializing platform accessory 'In-Law'...
Initializing platform accessory 'Living Room'...
Initializing platform accessory 'Family Room'...
Initializing platform accessory 'Master Bedroom'...
Initializing platform accessory 'Upstairs Hallway'...
Initializing platform accessory 'Kitchen'...

So my Nest name on the Nest itself is "Office", the HomeKit Room name is "Office", and the HomeKit Accessory name is "Office Nest". Keep in mind, this all worked perfectly before I updated to the latest homebridge-nest release. However, the old plugin never pulled the name from the Nest API like it does now. In the old plugin, I had to use Elgato Eve to map each Nest s/n to the HomeKit Room and name them accordingly.

I wonder if that is screwing it up. If so, it doesn't make sense for me to change the names of the Nests themselves - they have been like that for 3 1/2 years now and the family will get confused. It doesn't make sense to rename the HomeKit Room something other than "Office" or "Kitchen" since that is what room they are in. Trying to think of a way that this would logically work if the issue is truly the Nest name and HomeKit Room name being the same that is making this not work now. Any way to send the Nest s/n as an option like before in order to map it the old way? I understand this isn't desirable for most people (most don't have 7 Nests!) but being able to set an option in code (not the default setting of course) might work for all?

![img_4544](https://cloud.githubusercontent.com/assets/16343534/12225144/4afd0d02-b7d2-11e5-8813-0f2380ebbf42.jpg)
![img_4545](https://cloud.githubusercontent.com/assets/16343534/12225146/4b1d9d10-b7d2-11e5-9682-347fa3e4abba.jpg)
![img_4546](https://cloud.githubusercontent.com/assets/16343534/12225147/4b1fb2b2-b7d2-11e5-8a07-0ad4357d7cbb.jpg)
![img_4547](https://cloud.githubusercontent.com/assets/16343534/12225145/4b130102-b7d2-11e5-8dcd-85d4c74707bc.jpg)

**Comment by JerGitHub** [comment]
Also keep in mind that the "How warm is the Office?" works vs. "What's the temperature of the Office?" which makes me think the Nest name and HomeKit Room name aren't getting confused?

**Comment by KraigM** [comment]
As stated in the note above, you can use the Insteon+ app to change the name Siri uses.  It will leave the name in the Nest app alone and you can go back to using Elgato

**Comment by KraigM** [comment]
In the old api, if you didn't set the label which sounds like you didn't, it named each nest something like _Nest0551656138443_ so you actually couldn't use Siri to query the nest directly.  If you just called it by the type (i.e. _thermostat_) then it would look for a thermostat in that room/zone and assume that is what you mean.  So you can go back and label each something random like that.

Keep in mind, that name was a temp work around to handle people who had more then one Nest and didn't label them. In other words, it was a bug that got fixed in this release.  Going back to it would cause issues for many more other people.

**Comment by KraigM** [comment]
Sorry I edited that last comment so reread if you have already read through it

**Comment by JerGitHub** [comment]
Thanks and Yes, with the old API, I did set the label after it read all 7 Nests into HomeKit. That's what I was saying above - "However, the old plugin never pulled the name from the Nest API like it does now. In the old plugin, I had to use Elgato Eve to map each Nest s/n to the HomeKit Room and name them accordingly."

I was just calling it the Nest s/n where you used an example of "Nest0551656138443".

Using your example above, in the old API - I renamed "Nest0551656138443" to "Office Nest" for the HomeKit Accessory Name (aka the name Siri uses) and created the room "Office" within HomeKit. When I queried "What is the temperature in the Office?" It would give me the current temp and not the target temp.

My point was - in the new API - It pulls in the Nest label aka the HomeKit Accessory Name (aka the name Siri uses). In my case that Nest name is set to "Office". When I create a HomeKit Room named "Office" I renamed the HomeKit Accessory Name in the Eve app to "Office Nest" so the naming convention would be exactly the same as it was using the old API. Unfortunately, this isn't working with the new API.

Make sense?

**Comment by KraigM** [comment]
Yes but I think there is a diff between the Siri name and the Accessory name (I think this was to allow you to label it in the app as one thing but control it from Siri as another?).  So when you renamed it in the old API it may have just been one and not the other, so Siri may have derived different meanings from what you used to say.  Please try downloading Insteon+ and see what it says

![img_0338](https://cloud.githubusercontent.com/assets/7624028/12250607/ed1146f6-b88d-11e5-9529-9a7706489ec3.PNG)

**Comment by JerGitHub** [comment]
OK just downloaded Insteon+ and I didn't change a thing (except the icon!). Here's what it came up as....
![img_4554](https://cloud.githubusercontent.com/assets/16343534/12280238/5c6394e2-b95a-11e5-96f3-6f557b969fb0.PNG)

**Comment by KraigM** [comment]
So the way HomeKit works, there is the nest device which right now has just the thermostat service but both of which have names. I believe what they call Siri control is the service name. Given that it is Siri now has two things named "office" (the room and the termostat on the office nest device), Siri is prob best guessing that you are talking about the termostat when you say "office" when it is related to temperature. So on the old api, your thermostat name (not the device name but the service) was still that long one whereas the device name was office nest (since eve doesn't give you the option to rename the thermostat). So you need to name the thermostat something like the s/n

**Comment by KraigM** [comment]
In other words,  _Anther option to fix the name is through HomeKit. HomeKit allows you to rename Accessories and Services, but it requires an app like Insteon+ that has the ability to change the name._ (as sated in the readme)

**Comment by KraigM** [comment]
Hopefully that helped?  If not, let me know :smile:

**Comment by JerGitHub** [comment]
Apologies I never responded to this. I was troubleshooting the LiftMaster plugin at the same time.

Not a fan of how Apple is handling the naming in HomeKit. It's definitely confusing. Not sure why the Accessory Name can't be the Siri/Control name? Same thing happened with the new homebridge-liftmaster plugin that pulls all of my liftmaster door names as the Accessory Name and doesn't allow me to query correctly with Siri/HomeKit until I change all the Siri/Control Names.
