### ISSUE TITLE
Nest will not change temperatures when in auto away

### ISSUE THREAD

**Issue by thewings** [KraigM/homebridge-nest#28]
If you ask siri to set a temperature and nest happens to be in auto-away or away mode, it will reply "Sorry, I wasn't able to find any thermostats this time". I suggest adding a command to set the mode to home before sending the temperature change request. If you are asking siri to change the temperature, there is a good chance that you don't want it in auto-away or away mode anyways.

**Comment by KraigM** [comment]
Completed and will be in next release (1.1.0)
