### ISSUE TITLE
Revert back to old api

### ISSUE THREAD

**Issue by EnigmaFx** [KraigM/homebridge-nest#31]
how do I remove the now api  install the legacy version of nest plugin mate? running sudo npm install -g homebridge-nest im assuming installed the new version? i had everything running just fine before upgrading my system, upon trying to reinstall nest api i get all these errors http://d.pr/i/1j8Gi looking at the git-page it looks like there are a tone of steps i need to go through  to get this to work again would rather just stick with the old api for now i tried going through the steps for the new api I got to the point where I was registering the dev account in order to use the new api , and got stuck here -->  http://d.pr/i/i1lI <--  I dont know how to move forward so if there is no way to use the old api can someone please help me figure out what to do from here? thx in advance

**Comment by KraigM** [comment]
That has nothing to do with Nest or HomeBridge-Nest at all.  Looks like HomeBridge itself is crashing due to a bad config file.

**Comment by KraigM** [comment]
The old api is still in the new version.  Its only if you go thru the process of updating to the new api will it switch.  And even then it will still fall back to the old api if it is unable to properly setup the new api

**Comment by KraigM** [comment]
Helped via #slack and got @EnigmaFx up and running :smile:
