### ISSUE TITLE
Support Away feature in Nest bridge

### ISSUE THREAD

**Issue by brandwe** [KraigM/homebridge-nest#32]
Away / Home is not exposed in the HomeKit API currently.

**Comment by brandwe** [comment]
This is in the code but not yet available in HomeKit according to the API docs:

https://developer.apple.com/library/prerelease/watchos/documentation/HomeKit/Reference/HMCharacteristic_Class/index.html#//apple_ref/c/tdef/HMCharacteristicValueHeatingCooling

```
typedef NS_ENUM (NSInteger,
   HMCharacteristicValueHeatingCooling ) {
   HMCharacteristicValueHeatingCoolingOff = 0,
   HMCharacteristicValueHeatingCoolingHeat,
   HMCharacteristicValueHeatingCoolingCool,
   HMCharacteristicValueHeatingCoolingAuto,
}
```

```
typedef NS_ENUM (NSInteger,
   HMCharacteristicValueTemperatureUnit ) {
   HMCharacteristicValueTemperatureUnitCelsius = 0,
   HMCharacteristicValueTemperatureUnitFahrenheit,
}
```

**Comment by KraigM** [comment]
We do technically support this at the moment but its a custom characteristic.  If you use the Insteon+ app, you can see the data but it is not labeled.  If you use Elgato Eve app, it is displayed properly and can even be controlled.  But this does not use the same characteristic code that Ecobee 3 uses (which has hopefully been Apple approved, just not announced).  

We will switch it to use the proper code once we can figure out what it is or it is announced.

I know some users have even gotten things to trigger based on our current custom "IsAway" characteristic (#21).
