### ISSUE TITLE
Make the Nest server configurable

### ISSUE THREAD

**Issue by khkremer** [KraigM/homebridge-nest#39]
I don't want to break the #1 fight club rule... But let's assume that the guy who wrote this post is correct, and there is a Nest beta program, would it be possible to make the Nest server configurable, so that somebody who participates in something that may or may not exist can also use the HomeBridge-Nest plug-in without having to modify the sources for every update? :)

Here is the post I am referring to:

https://www.domoticz.com/forum/viewtopic.php?t=9758

**Comment by KraigM** [comment]
Dude... there are rules :smile: 

It would have to be with the new API but that might be possible.  Right now, it authorizes with https://api.home.nest.com/oauth2/access_token and connects with wss://developer-api.nest.com so if you know the addresses to replace those then it should be possible.

**Comment by khkremer** [comment]
I am not aware of any way to create access tokens for the field test server. It does work with the old API buy just redirecting the server from home.nest.com to home.ft.nest.com. The field test account uses a separate set of credentials. Oh well, I'll just edit the file again :) Just don't remove the old access method. 

Thanks.

**Comment by KraigM** [comment]
Are you editing something in the files that makes it work? Which files? What are you editing?

**Comment by khkremer** [comment]
In homebridge-nest/node_modules/unofficial-nest-api/index.js I change the
home.nest.com to home.ft.nest.com:

    var login = function (username, password, done) {

        nestPost({

          hostname: 'home.ft.nest.com',

          port: 443,

**Comment by KraigM** [comment]
Thats the OLD api.  We def can't do anything about that.  You really should switch to the new api.

I would guess auth url would be:
`https://api.home.ft.nest.com/oauth2/access_token`

And maybe the firebase url would be:
` wss://developer-api.ft.nest.com`

If you switch to the api and test those out manually then I would be happy to add an option in there for you guys.  But given I'm not part of ...the club, I can't test it out myself

**Comment by khkremer** [comment]
Yes, that's the old API - because I have not yet found a way to use the new
API with the field test server.

Thanks.

**Comment by KraigM** [comment]
Well no new dev is being done on the old api.  Can you see if the two url's above allow you to use the new api?

**Comment by khkremer** [comment]
No it's not working - that's what I meant by " I have not yet found a way
to use the new API with the field test server. "


Karl Heinz Kremer
PDF Acrobatics Without a Net
PDF Software Development, Training and More...

khk@khk.net
http://www.khkonsulting.com

**Comment by KraigM** [comment]
Well that stinks.  Is there any beta forum that you can use to ask them?  You would think they would have some sort of firebase setup for beta testers.  I mean that functionality has to be tested too.

**Comment by khkremer** [comment]
You would think so :) But at this point, the old system is all that works.

Thanks.

**Comment by KraigM** [comment]
So is there a forum?

**Comment by khkremer** [comment]
If there were a fight club, there probably would be a private forum :)  I
can of course not share anything that's discussed there, and unfortunately,
at this point only the old login system works. I guess you can close this.
Thanks.


Karl Heinz Kremer
PDF Acrobatics Without a Net
PDF Software Development, Training and More...

khk@khk.net
http://www.khkonsulting.com

**Comment by KraigM** [comment]
Well I know with Apple fight club, we can talk about fight club in the forum but not outside the forum.  Just thought you might be able to ask them how to access fight club via firebase.

**Comment by KraigM** [comment]
???

**Comment by khkremer** [comment]
Sorry, I though I had replied. There is no information available about how to access the new login system - all that was confirmed was that the old system works with a modified server path. As I said, you can close this issue.
