### ISSUE TITLE
oldaccessories fallback causing issues with authentication

### ISSUE THREAD

**Issue by karlentwistle** [KraigM/homebridge-nest#40]
Firstly - I just got homebridge-nest setup, I love it! The documentation provided is great. Thanks for making / maintaining this great plugin :+1:

However during setup I stumbled across an issue that confused me for a while. I'm still unsure why it occurred. My devices are as follows

* Nest protect 2nd generation 
* Nest learning thermostat 3rd generation

I was unable to follow steps

```
Run HomeBridge once (do not include the token in the config at this time) and you should find a log that says something like "CODE IS ONLY VALID ONCE! Update config to use {'token':'c.5ABsTpo88k5yfNIxZlh...'} instead." Copy the c.5ABsTpo88k5yfNIxZlh... portion to your HomeBridge config as the token in the Nest config
```

```
If the token is working correctly, you no longer NEED the other three configs (clientId, clientSecret, and code) nor the original username and password
```

I kept getting authentication issues, I *think* this might be because there is a legacy 'oldaccessories' devise in my setup. My aforementioned Nest Protect 2nd generation smoke detector.

To fix my issue I resorted to 
- make a POST request to: 
https://api.home.nest.com/oauth2/access_token?client_id=foo&code=AUTHORIZATION_CODE&client_secret=bar&grant_type=authorization_code 
- fetch auth token from response. 
- editing config.json to include token, *username* and *password*. 

Otherwise I keep getting the error message ```There was a problem authenticating with Nest.```

```json
   "platforms":[  
      {  
         "platform":"Nest",
         "token":"c.bla",
         "username":"me@example.com",
         "password":"password"
      }
   ]
```

If I'm correct and setups including any 'oldaccessories' will cause this issue it might be worth updating the README to reflect this or editing the error message https://github.com/KraigM/homebridge-nest/blob/master/index.js#L161

Just thought I'd post some friendly feedback because otherwise setup would have been a breeze. 

 Cheers

**Comment by KraigM** [comment]
Step 12 and 13 involve you obtaining a pin code instead of the token and then configuring the pin code first. Then in step 14, it will go run the post call for you and spit out the token (first time only) which then must be added to the config instead of the pin code.  Basically I set up the steps the way so that people wouldn't have to mess with POST requests given some may not even know what that means. 

Does that clear it up? Did I miss anything?

**Comment by KraigM** [comment]
Well let me know if you have any other follow up, questions, or suggestions on this.  Otherwise Im going to go ahead and close this.
