### ISSUE TITLE
Siri give erratic temperature in celsius

### ISSUE THREAD

**Issue by dvd2000k** [KraigM/homebridge-nest#41]
Hi, if i ask Siri to give me current home temperature it give me erratic answer:
Say 1919 celsius for 19,0 celsius
18,519 celsius for 18,5 celsius etc....
It always append the value 19...
Running on my Mac or my pi give me the same result.

How can i correct it?
Homebridge vers. 0.2.19
Homebridge-Nest 1.0.1

**Comment by KraigM** [comment]
Can you send some logs?

**Comment by dvd2000k** [comment]
Here is Homebridge log, temperature in homebridge is reported correctly, siri have problems report only current temperature.
Could be the decimal mark difference? e.g. 19,5 in italy, not 19.5 


Current temperature for Casa Castelmella is: 19 C
Current temperature for Casa Castelmella is: 19.5 C
Current humidity for Casa Castelmella is: 55%
Current heating for Casa Castelmella is: 0
Current temperature for Casa Castelmella is: 19 C
Current temperature for Casa Castelmella is: 19.5 C
[WeMo Platform] getOn: Illuminazione is on 
[WeMo Platform] getOn: WeMo Motion is off 
[WeMo Platform] getOn: Clima is off 
Current temperature for Casa Castelmella is: 20 C
[WeMo Platform] getOn: Clima is off 
[WeMo Platform] getOn: Illuminazione is on 
[WeMo Platform] getOn: WeMo Motion is off 
[WeMo Platform] setOn: Illuminazione to off
[WeMo Platform] Illuminazione binaryState: off
[WeMo Platform] setOn: Illuminazione to on
[WeMo Platform] Illuminazione binaryState: on
[WeMo Platform] getOn: Illuminazione is on 
[WeMo Platform] getOn: WeMo Motion is off 
[WeMo Platform] getOn: Clima is off 
[WeMo Platform] getOn: Illuminazione is on 
[WeMo Platform] getOn: WeMo Motion is off 
[WeMo Platform] getOn: Clima is off 
[WeMo Platform] getOn: Clima is off 
[WeMo Platform] getOn: Illuminazione is on 
[WeMo Platform] getOn: WeMo Motion is off 
[WeMo Platform] getOn: Illuminazione is on 
[WeMo Platform] getOn: WeMo Motion is off 
[WeMo Platform] getOn: Clima is off 
[WeMo Platform] setOn: Illuminazione to off
[WeMo Platform] Illuminazione binaryState: off
[WeMo Platform] setOn: Illuminazione to on
[WeMo Platform] Illuminazione binaryState: on
Target temperature for Casa Castelmella is: 20 C
Target temperature for Casa Castelmella is: 19.5 C
Target temperature for Casa Castelmella is: 20 C
Target temperature for Casa Castelmella is: 19.5 C
[WeMo Platform] getOn: Illuminazione is on 
[WeMo Platform] getOn: WeMo Motion is off 
[WeMo Platform] getOn: Clima is off 
[WeMo Platform] setOn: Illuminazione to off
[WeMo Platform] Illuminazione binaryState: off
[WeMo Platform] setOn: Illuminazione to on
[WeMo Platform] Illuminazione binaryState: on
[WeMo Platform] getOn: Illuminazione is on 
[WeMo Platform] getOn: WeMo Motion is off 
[WeMo Platform] getOn: Clima is off 
[WeMo Platform] getOn: Clima is off 
[WeMo Platform] getOn: Illuminazione is on 
[WeMo Platform] getOn: WeMo Motion is off 
[WeMo Platform] setOn: Illuminazione to off
[WeMo Platform] Illuminazione binaryState: off
[WeMo Platform] setOn: Illuminazione to on
[WeMo Platform] Illuminazione binaryState: on
[WeMo Platform] setOn: Illuminazione to off
[WeMo Platform] Illuminazione binaryState: off
Current temperature for Casa Castelmella is: 19.5 C
Current temperature for Casa Castelmella is: 20 C
Current temperature for Casa Castelmella is: 19.5 C

**Comment by KraigM** [comment]
Well we send homekit a number not a string (so there is no decimal **.** or **,** :smile: 

Can you send a screenshot of the siri response when you get a bad response

**Comment by dvd2000k** [comment]
Ok,here is a screenshot of siri response:
![img_0533](https://cloud.githubusercontent.com/assets/17496560/13432430/d7e8ac80-dfcd-11e5-8c9d-0785ac1cf536.PNG)

**Comment by KraigM** [comment]
I assume you have restarted homebridge and all that jazz

**Comment by dvd2000k** [comment]
I have homebridge installed on my raspi and on my mac. Same result... :(

**Comment by KraigM** [comment]
Then I think I'm going to call in the reinforcements on this one bc Im not sure if its something with node, siri, homebridge, or homebridge-nest.  The logs are showing exactly what we send to homebridge so I can't think of any reason that would be happening.

@nfarina @KhaosT Any ideas?

**Comment by dvd2000k** [comment]
And if i ask siri about the current "target" temperature, the response is correct. Only with the current inside temperature i have this problem... The home app report both correct temperature. I also tried to restore iPhone to it's default, nothing changed. Tried on another iPhone, same thing.

**Comment by KraigM** [comment]
Do you have any other devices on homebridge and/or homekit?

**Comment by dvd2000k** [comment]
Yes, i have a wemo switch, wemo insight and wemo motion and Nest configured on homebridge. 
I have philips hue bridge 2.0 that is homekit ready.

On my mac i have node vers. 5.6.0
on my raspi 4.2.1

**Comment by dvd2000k** [comment]
and here is the answer for 19,5:
![img_0535](https://cloud.githubusercontent.com/assets/17496560/13438157/111f247e-dfe8-11e5-95ab-0ace5991f009.PNG)


and for 20C the answer is 2020C...

**Comment by dvd2000k** [comment]
Or could it be some sort of rounding problem?
I get 1818 for 18
18,519 for 18,5
1919 for 19
19,520 for 19,5
2020 for 20...

**Comment by KraigM** [comment]
What about the HomeKit apps (like Insteon+)? What do they display?

**Comment by dvd2000k** [comment]
All the apps display the correct temperature. Only Siri have problems to tell the correct temperature.

**Comment by KraigM** [comment]
Then this is very likely a Siri bug.  I would submit a request to Apple

**Comment by dvd2000k** [comment]
I have tried now to change Siri from Italian to english. She tell the correct temperature! It's a Siri bug for Italian. Thankyou!

**Comment by KraigM** [comment]
Glad to hear (that its not my bug) :smile:
