### ISSUE TITLE
How to config with multiple Nest thermostats

### ISSUE THREAD

**Issue by hln98** [KraigM/homebridge-nest#42]
Hi,

I got one Nest running with your home bridge-nest with the new API as suggested.  In my config.json file I have a token, clientId and clientSecret etc like the text below:

If I add another Nest thermostat # 2 to the house, is the following correct?  I will still use the same token?  also what do I put for "platform" for the 2nd Nest?  Please advice.

"platforms": [
	{
		"platform": "Nest",
		
		"token" : "c.5ABsTpo88k5yfNIxZlh...",
		
		"clientId": "developer client id",
		"clientSecret": "developer client secret.",
		"code": "Pin Code",
		
		"username" : "username",
		"password" : "password"
	},

	{
		"platform": "Nest number 2 goes here?",
		
		"token" : "c.5ABsTpo88k5yfNIxZlh...",
		
		"clientId": "developer client id",
		"clientSecret": "developer client secret.",
		"code": "Pin Code",
		
		"username" : "username",
		"password" : "password"
	}

],

**Comment by KraigM** [comment]
No the platform does everything automatically. In the homebridge world, platforms are able to load multiple accessories and usually do so automatically.  So you usually do not duplicate platforms (usually).

**Comment by hln98** [comment]
KraigM,

To be super clear, as you tech folks are never very clear :), what I have in my config.json now that works with "1" Nest, will work with "multiple" Nest thermostats, correct?

"platforms": [
{
"platform": "Nest",

    "token" : "c.5ABsTpo88k5yfNIxZlh...",

    "clientId": "developer client id",
    "clientSecret": "developer client secret.",
    "code": "Pin Code",

    "username" : "username",
    "password" : "password"
}

],

**Comment by KraigM** [comment]
Yes, if the above config works for one thermostat on your account, then it will also automatically add all thermostats on your Nest account.

Side note, once you have a working token (by following the New API guide on the README), you no longer need clientId, clientSecret, or code.  You also will no longer need username and password as it is for the old api, but if you keep username/password and the new API fails to setup, it will fall back to the old api if it can (so u/p will still be used if something goes wrong but it is not needed if everything is working).

**Comment by KraigM** [comment]
Hopefully that is clear enough for you :smile:

**Comment by KraigM** [comment]
Going ahead and closing this for now.  If you have any further questions, feel free to ask.

**Comment by vacooley** [comment]
Hello, Just got Homebridge working on a pi 3 with Jesse. 
I have the same general question about handling multiple thermostats on the same Nest location. I have 3 Nest thermostats in the house. Siri can only address them together.

"set temperature to 78 degrees" results in Siri responding with "OK... I set all thermostats to about 78 degrees"

"set downstairs thermostat to 78 degrees" results in "Sorry.... I was not able to find and thermostats this time".

Is there a way to configure home bridge so that I can address a specific thermostat?

**Comment by toshibochan** [comment]
You add the room and add the thermostat the the room? I have 3 nest to and work great! I just say "set bedroom temperature to 70" or living room or family room to 70!

**Comment by toshibochan** [comment]
Add "downstairs" room and add nest in the room! And just say "set downstairs temperature to 70"

**Comment by vacooley** [comment]
What IOS app are you using? Do you configure the rooms in the IOS app or in home bridge?

I am using Ezzi Home Control. It does not have 'rooms'. It has 'PINS' instead. Not sure if that is the same.

**Comment by toshibochan** [comment]
Insteon+

**Comment by toshibochan** [comment]
Ezzi Home Control Is complicated. Use insteon+

**Comment by toshibochan** [comment]
PINS on Ezzi Home Control is the accessories not room

**Comment by toshibochan** [comment]
Work?

**Comment by vacooley** [comment]
Yes. I also got the iDevices app to work as well.
I can now access the Thermostat by room.
Thanks.

**Comment by toshibochan** [comment]
Great! Glad work!
