### ISSUE TITLE
How to update to latest version of home bridge-nest?

### ISSUE THREAD

**Issue by hln98** [KraigM/homebridge-nest#43]
I am a noob with Linux.  How do I update to the latest code of your home bridge-nest?

Is this correct?
sudo npm update -g homebridge-nest

**Comment by KraigM** [comment]
sudo npm install  -g homebridge-nest

**Comment by KraigM** [comment]
You might also want to look at my new project.  Its very early stage and thus you might have to go back and fix up things afterwards.  But hopefully it will be stable and fully tested in the near future.

https://github.com/KraigM/HomeBridgeController

**Comment by KraigM** [comment]
Hopefully that helps.  Im going to close this for now but feel free to follow up
