### ISSUE TITLE
Firebase error

### ISSUE THREAD

**Issue by Jo3ytjuh** [KraigM/homebridge-nest#44]
Hi there, i can't change the temp.. When i say the temperture it currently is set to, he says he do it.. But if i say another temperture he gives the following error : "FIREBASE WARNING: set at /devices/thermostats/#MASKED#/target_temperature_c failed: blocked"

Any idea ?.. 
Made it up with the new api (as fr as i know) and removed my username and password from the config.json

**Comment by Jo3ytjuh** [comment]
Btw, legancy mode is working....

**Comment by Jo3ytjuh** [comment]
I would like to use the new api, so i can remove the username and password from the file... Cause its send trough the internet .. Or am i wrong ? Still like to use the new api..

**Comment by KraigM** [comment]
Did you make sure the permissions were added to your app in the Nest Dev website (Step 8 - Permission)?

**Comment by Jo3ytjuh** [comment]
Hey KraigM thanks for the fast reply..

Permissions are good, if ill set the legacy mode (username and password) then its working... But with the pin it isn't.

**Comment by KraigM** [comment]
Pin only works once. On that run, there will be a console print out with the token to add to your config.  Remove any token you have, go back to step 12 to get a new pin code, and then just continue again from there, making sure to copy the token from the console (step 14).  

I'm going to attempt to setup [HomeBridge Controller](https://github.com/KraigM/homebridgecontroller) to greatly simplify this process in the future.

**Comment by KraigM** [comment]
https://github.com/KraigM/HomeBridgeController/issues/28

**Comment by Nnk2** [comment]
I get the same error now (was working fine earlier today: FIREBASE WARNING: set at /devices/thermostats/****number withheld by me**/**target_temperature_c failed: blocked

I have tried reauthorizing with nest (no change) and will try legacy mode now ..

**Comment by Nnk2** [comment]
Legacy mode works for me too ... (But I hope you get the new api working again ..)

**Comment by KraigM** [comment]
Its working for many others. 

@Nnk2 if it was working for you and then stopped, you might have reached to write limit.  Nest limits you on how many changes you can make within a short period.  Once the short period ends, you are able to write again.  To know if that is the case, make a change using the Nest app and verify that it shows up on homebridge.  If thats the case, then it is working as expected

**Comment by Nnk2** [comment]
@KraigM: That was it, thank you!  (I guess I should not be testing that much ;-) ... All is well now ..

**Comment by KraigM** [comment]
@Nnk2 Good to hear
@Jo3ytjuh hopefully you are good now too?

Let me know if this is still on going.  Closing for now.
