### ISSUE TITLE
Nest Cam - can't set Away

### ISSUE THREAD

**Issue by leoneleone** [KraigM/homebridge-nest#48]
Thank you for updating the plugin to include Nest Cams as well. 

The issue I'm having is that I do not see an Away toggle after adding my Nest Cams. The show up in my HomeKit config but they do not have the Away Characteristic.
I do not have a best Thermostat. I believe  the best-camera-accessory.js doesn't include Away functionality. 

Can you add Away functionality to Nest Cam please?

Many Thanks

**Comment by KraigM** [comment]
I really want to figure out the proper solution for Home/Away.

For now I will add it to cam as well.  That way it will hold you off until we figure out the proper handling :smile:

**Comment by KraigM** [comment]
Released in 1.1.1

**Comment by leoneleone** [comment]
Thanks. That would be amazing!

Have you thought of adding Home/Away as separate switchService? Perhaps with its own nest-home-accessory.js file within the lib folder? It could show up in HomeKit as "NestHome", etc.
That way it can function within HomeKit as Home/Away toggle independent of any devices, but affecting the entire "Nest structure".

Just thinking out loud here 😉

**Comment by KraigM** [comment]
No I like that, I was just wanting to wait to figure out how we are supposed to handle away.  I know Ecobee does it

**Comment by KraigM** [comment]
Btw in case you missed it above, I released it

**Comment by leoneleone** [comment]
just updated the plugin.

I get an error:
[TypeError: this.addAwayCharacteristic is not a function]

**Comment by KraigM** [comment]
Doesn't happen on my side.  Try restarting? reinstalling?

**Comment by leoneleone** [comment]
My mistake. 
I had updated only the cam file in the lib folder. 
Updating the entire plugin fixed the error. 
All is working as expected now. 
Thanks a million. You're amazing!

I really this an independent Nest Accessory for the Home/Away function is the best solution. It would streamline its use in HomeKit until Apple supports such a function.

**Comment by leoneleone** [comment]
"NestAway" as a separate accessory can then be easily added to HomeKit scenes and would affect all nest accessories within the nest home. I'd add it to my "I'm home" and "I'm leaving" scenes.

If it is made a simple Service.Switch using only Characteristic.On, then one can also use Siri commands to initiate it.
I would expect these Siri commands to work:
"Turn on Nest Away", "Turn off Nest Away"
"Switch Nest Away on", "Switch Nest Away off"

The only stumbling block would be if you used the Siri command "Turn everything off" when leaving the house. That would also turn "Nest Away" off - or change the Nest setting to "Home", doing the exact opposite of what you would want it do in that particular situation.

**Comment by obiwade** [comment]
So what became of this? I am using MyTouchHome. The options I see with the cameras are a grayed out "motion detected" option and an "N/A" option I can toggle on/off......

**Comment by obiwade** [comment]
https://github.com/KraigM/homebridge-nest/issues/2


Nevermind
