### ISSUE TITLE
Cannot connect to homebridge nest even though it is running correctly

### ISSUE THREAD

**Issue by spopky** [KraigM/homebridge-nest#50]
Hi 

I am very new to this. My homebridge set up finally looks correct after many tweaks but it does not show up in my "Devices" app on my iPhone when I click add new device. Can anyone offer any help here? It would be greatly appreciated.

Last login: Sat Mar 19 18:20:11 on ttys000
Steves-MBP:~ stevepopky$ homebridge
[3/19/2016, 6:41:34 PM] Loaded plugin: homebridge-nest
[3/19/2016, 6:41:34 PM] Registering platform 'homebridge-nest.Nest'
[3/19/2016, 6:41:34 PM] ---
[3/19/2016, 6:41:34 PM] Loaded config.json with 0 accessories and 1 platforms.
[3/19/2016, 6:41:34 PM] ---
[3/19/2016, 6:41:34 PM] Loading 1 platforms...
[3/19/2016, 6:41:34 PM] Initializing Nest platform...
[3/19/2016, 6:41:34 PM] Fetching Nest devices.
[3/19/2016, 6:41:35 PM] Software version for Living Room Thermostat is: 5.1.8-3
[3/19/2016, 6:41:35 PM] Temperature unit for Living Room Thermostat is: Fahrenheit
[3/19/2016, 6:41:35 PM] Current temperature for Living Room Thermostat is: 73 F
[3/19/2016, 6:41:35 PM] Current humidity for Living Room Thermostat is: 25%
[3/19/2016, 6:41:35 PM] Target temperature for Living Room Thermostat is: 72 F
[3/19/2016, 6:41:35 PM] Initializing platform accessory 'Living Room Thermostat'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 987-65-432 │     
    └────────────┘     
                       
[3/19/2016, 6:41:35 PM] Homebridge is running on port 51826.

Thank you so much.

**Comment by KraigM** [comment]
Well if you have had some false starts, I recommend changing the bridge username in your homebridge config (just change one of the numbers to a different number) and restart.

**Comment by spopky** [comment]
That worked! Thank you so much. Now I have one more issue. The terminal readout I pasted above shows temp in Farenheit, but in the Devices app it shows as celsius. Anyway to change that?

**Comment by KraigM** [comment]
its prob what app you are using.  Try Insteon+ (at least to see if that is the issue).

**Comment by spopky** [comment]
I tried insteon and it fixed that issue but it seems every time I fix one
another pops up. It shows the temp in Fahrenheit now but it won't actually
control the nest. Sorry to keep bugging you with the issues, I really
appreciate your help. Siri also won't work. It tells me that there's no
thermostat to control.

On Saturday, March 19, 2016, KraigM <notifications@github.com> wrote:

> its prob what app you are using. Try Insteon+ (at least to see if that is
> the issue).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/KraigM/homebridge-nest/issues/50#issuecomment-198804934>
>


-- 
Steve Popky
Tombstonecity
631-903-3113

**Comment by spopky** [comment]
It's connected to the nest, because when I use the nest app to set it to
cool it shows that it's cooling and it shows the target temp but it won't
let me change anything through insteon.

On Saturday, March 19, 2016, Steve Popky <steve.popky@gmail.com> wrote:

> I tried insteon and it fixed that issue but it seems every time I fix one
> another pops up. It shows the temp in Fahrenheit now but it won't actually
> control the nest. Sorry to keep bugging you with the issues, I really
> appreciate your help. Siri also won't work. It tells me that there's no
> thermostat to control.
>
> On Saturday, March 19, 2016, KraigM <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> its prob what app you are using. Try Insteon+ (at least to see if that is
>> the issue).
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/KraigM/homebridge-nest/issues/50#issuecomment-198804934>
>>
>
>
> --
> Steve Popky
> Tombstonecity
> 631-903-3113
>
>

-- 
Steve Popky
Tombstonecity
631-903-3113

**Comment by KraigM** [comment]
jump on the [slack](https://homebridge-slackin.herokuapp.com/) homebridge-nest channel

**Comment by spopky** [comment]
Ok I'm on. Not sure what to do with it though again I'm new to all this.

On Saturday, March 19, 2016, KraigM <notifications@github.com> wrote:

> jump on the slack <https://homebridge-slackin.herokuapp.com/>
> homebridge-nest channel
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/KraigM/homebridge-nest/issues/50#issuecomment-198810216>
>


-- 
Steve Popky
Tombstonecity
631-903-3113

**Comment by KraigM** [comment]
Resolved on Slack
