### ISSUE TITLE
Doesn't seem to load with my config file

### ISSUE THREAD

**Issue by simonrb2000** [KraigM/homebridge-nest#51]
I get this error message when I try and load Homebridge with just the nest plugin.

`/usr/local/lib/node_modules/homebridge/lib/server.js:124
    throw err;
    ^

SyntaxError: Unexpected token  
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:118:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3`

This is my config file, I have tried it with and without the token. The config file passes the JSON website check so it is valid. Thank you in advance
{
	"bridge": {
		"name": "Homebridge",
		"username": "DD: 33: 4E: F4: DF: 31 ",
		"port": 51927,
		"pin": "031-45-154"
	},

	"platforms":  [{
		"platform":   "Nest",

		"clientId":   "2fd1eef9-e990-4680-9114-c696",
		"clientSecret":   "5YVLGQuspgfpbbcZ",
		"code":   "PHX",

		"username" :   "my email",
		"password" :   "my password!"
	}]
}

**Comment by KraigM** [comment]
Not sure that client, secret, code combo are valid but even if they are, it only works once. 

I updated [HomeBridgeController](https://github.com/KraigM/homebridgecontroller) to authenticate Nest for you (you don't even need to create a Dev account anymore)

**Comment by simonrb2000** [comment]
Hey,

Oh ok, no the client and security code are not correct as I deleted some of the characters on the post as not sure if anyone could access my neat account, my config file has the whole info in it.

How can I get it working? Could you send an example config file? 

Really appreciate this. 

Kind Regards
Simon

**Comment by KraigM** [comment]
To reiterate: "I updated HomeBridgeController to authenticate Nest for you (you don't even need to create a Dev account anymore)". Just go set that up (much easier) and then it has one button to auth nest

**Comment by simonrb2000** [comment]
Sorry I don't quite understand. How do I setup the config file for homebridge? That's the issue I'm having. I have domoticz plugin running fine but every time I try load the Nest plugin it fails. I removed all traces of the Domoticz plugin just so I could get Nest working on its own but still no luck. 

Thank you.

**Comment by simonrb2000** [comment]
Ah, homebridgecontroller is a new addon thingy. Makes sense now! Never heard of it before. Looks promising.. I shall give it a go. 

Thank you.

**Comment by simonrb2000** [comment]
Hi,

I have installed the homebridgecontroller however I still cannot get anything working now. I am so confused with it all. I had domoticz working well, since installing the homebridgecontroller I have lost everything. All I wanted to do was setup the Nest as well as Domoticz but its all getting over complicated. I just need help with the config file. How do I set that up with homebridgecontroller and get my domoticz control back? I did install the mac app, it sees my home bridge setup but I can’t edit or do anything with it.

Thanks

**Comment by KraigM** [comment]
Make this your config and then you can add Nest platform via the app:

```
{

	"bridge": {
		"name": "Homebridge",
		"username": "DD: 33: 4E: F4: DF: 31 ",
		"port": 51927,
		"pin": "031-45-154"
	},

	"description": "ConfigurationfileforDomoticzplatform.",
	"platforms": [{
		"platform": "Domoticz",
		"name": "Domoticz",
		"server": "127.0.0.1",
		"port": "8080",
		"roomid": "4",
		"loadscenes": "0"
	},
	{
		"platform" : "HomeBridgeControllerLink"
	}]
}
```

**Comment by KraigM** [comment]
The app was originally designed to help people who don't understand JSON :smile:

**Comment by simonrb2000** [comment]
Thank you. I reverted to my original config file and got domoticz working again. Then updated my homebridge to the latest version and since then it doesn't even read my original config file which is strange as it was working before the update. Says my username isn't valid yet it is.. 

Very very strange.

**Comment by KraigM** [comment]
It's your bridge username that is incorrect. You have spaces after the colons. Should not be any spaces between the double quotes

**Comment by simonrb2000** [comment]
That's the one. I have removed the spaces and it still does the the same.

**Comment by simonrb2000** [comment]
I have just tried the config you suggested, with and without the spaces and this is what I get back.

3/28/2016, 11:45:54 PM] ---
[3/28/2016, 11:46:04 PM] Loaded plugin: homebridge-nest
[3/28/2016, 11:46:04 PM] Registering platform 'homebridge-nest.Nest'
[3/28/2016, 11:46:04 PM] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:184
      throw new Error('Not a valid username: ' + username + '. Must be 6 pairs of colon-' +
      ^

Error: Not a valid username: DD:33:4E:F4:DF:31 . Must be 6 pairs of colon-separated hexadecimal chars (A-F 0-9), like a MAC address.
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:184:13)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
pi@raspberrypi ~ $

**Comment by simonrb2000** [comment]
Got it running, removed the space at the end of the Mac address. Thanks.. Now try and get nest to run..

**Comment by simonrb2000** [comment]
I have this but how do I setup the nest plugin?



Cheers

**Comment by KraigM** [comment]
Use this as your config:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "DD:33:4E:F4:DF:31",
        "port": 51927,
        "pin": "031-45-154"
    },
    "platforms": [{
        "platform": "Domoticz",
        "name": "Domoticz",
        "server": "127.0.0.1",
        "port": "8080",
        "roomid": "4",
        "loadscenes": "0"
    },
    {
        "platform" : "HomeBridgeControllerLink"
    }]
}
```

Nothing more, nothing less.

Then:

1. Restart homebridge

2. Run HomeBridgeController

3. Select your homebridge

4. Press the `+` button on the bottom

5. Choose Nest

6. Press the `Authenticate` button on the Info tab 

7. File (menu) > Save

8. Hub (menu) > Restart Hub

**Comment by KraigM** [comment]
The `Authenticate` button will take you through logging in and authorizing homebridge.  Once you authorize it, it will take you back to the app and fill in the proper token for you.

**Comment by KraigM** [comment]
on the + button, you need to choose `Add Platform` since nest is a platform

**Comment by simonrb2000** [comment]
Ha, didn’t see the + and - at the bottom. When I hit + I get add platform, add accessory and install plugin. First two don’t do anything and the install plugin gives me a blank window with a search. When I search nest I get an object error message.

**Comment by simonrb2000** [comment]
Ignore last message. I closed down the app on the mac and reloaded it, selected home bridge and now it works. Lets see if I can add my nest :)

Thanks a million.

**Comment by simonrb2000** [comment]
Well Thank you so much for your help and patience. I can now turn my heating on and off using Siri! Wonderful. Only thing is I have duplicates of every item from Domoticz in homekit. One of them is contactable and the other isn’t. I assume its because I updated homebridge. Im thinking of deleting the persist folder and wiping my homekit and starting again. Shouldn’t take too long.

Lastly, command wise, can we set schedules for the heating to come on like. “Turn the thermostat to 22 degrees at 8am?” That would be handy. I did ask and it says it can’t schedule commands. I’m assuming thats Apple not allowing this.. 

Thanks again by the way, keep up the good work. Looking forward to the future with homebridge and with all the development to homebridgecontroller.

**Comment by KraigM** [comment]
Schedules work.  They are just based on 'Scenes'.  You create a HomeKit Scene for something like 'Good Morning' (one of the defaults) and then and things you want to happen on 'Good Morning' (set thermostat, turn on lights, etc).  Then you can not only schedule when you want 'Good Morning' to come on automatically but you can also tell Siri 'Good Morning' and Siri will set that scene for you immediately.

For instance, I have a 'Good Night' set up so I tell Siri 'Good Night' and Siri turns off my stops my AppleTV and puts it to sleep (HarmonyHub), turns off my TV/Receiver (HarmonyHub), turns off my porch light and street light (Hue), turns off my living room lights (Hue), and sets my thermostat (Nest).

**Comment by simonrb2000** [comment]
Oh I have that all setup. I meant can I say set my thermostat to come on at 22 at 8am tomorrow morning? I was hoping it could interact with the thermostats programming. Maybe Nest and/or Apple haven't released that as an API. I found the learning side of the thermostat useless as all of us work odd shifts so it couldn't learn a pattern. Therefore I have to program it every night to come on in the morning at whatever time. If we are getting up at 6 I set it to 22 degrees for 6am with the nest app then it comes on about 05:30 to warm the house to 22 degrees for 6am. I guess that isn't possible. 

Cheers

**Comment by KraigM** [comment]
I don't think you read my message carefully enough.  By "sets my thermostat", I mean "sets my thermostat to 71 degrees [because I'm American :stuck_out_tongue_winking_eye: ]". 

Maybe this will be clearer YES YOU CAN DO WHAT YOU ARE ASKING JUST NOT DIRECTLY :smile: 

You have to create a *HomeKit Scene* that sets the temperature to the degree you want (22 or whatever).  Then set a schedule of when to set the scene (8 am or whatever). So the net-net is it will set you Nest to 22 degrees at 8 am.

**Comment by simonrb2000** [comment]
I did read the message. I was asking if you could directly set nest schedule from Siri as I like that fact I set it to 22 degrees at 6 am for when we get up and it's that temperature because the thermostat knows what time to turn the heating on to warm the house up by 6am. Your work around doesn't do that. 

Don't get me wrong, I can use the nest app and just program it every night before bed, or use your work around and tell it to come on 45 mins earlier or something. Thought I'd ask the question as it would have been great if that part of the nest api was exposed but I'm guessing it isn't. 

Thanks again.

**Comment by KraigM** [comment]
No it is not part of Nest's api as far as Im aware.  They are very limited on what they let you set on the official API.

So you are not wanting it to set the temperature at particular time but for it to "preheated" by that time?

**Comment by simonrb2000** [comment]
That's exactly it. I should have worded it better.
