### ISSUE TITLE
Nest Cams

### ISSUE THREAD

**Issue by obiwade** [KraigM/homebridge-nest#57]
The nestcams show up in Hesperus with an away toggle even. 

Anyone figured out the voice commands? Can't seem to make it work..... 

I do not have the thermostat, but I'm guessing it's the key..........

**Comment by KraigM** [comment]
The Nest Cam integration is really only good for HomeKit triggers at the moment (as in "When motion is detected by this camera, turn on that HomeKit light").  The only thing Nest supports via the API is read only data.  

What were you looking to do via voice commands?

**Comment by obiwade** [comment]
Thanks for the clarification! Wasn't looking to do anything in particular just curious as to any features other than displaying that I have cameras! Haven't convinced the wife we need a thermostat yet...

**Comment by KraigM** [comment]
If you have something else that is hooked to HomeKit (lights, thermostat, fans, etc) then, yes, using it to trigger other devices is a very handy thing (i.e. "If everyone has left the room then turn these devices off" or "If I enter the bedroom after 9pm then auto set the thermostat to 71").

**Comment by KraigM** [comment]
Closing issue since question seems to be answered
