### ISSUE TITLE
[Nest] Update to Device: undefined type: undefined

### ISSUE THREAD

**Issue by druchtie** [KraigM/homebridge-nest#6]
The Homebridge can't generatie code.
How to fix?
<img width="580" alt="screen shot 2015-12-08 at 22 40 33" src="https://cloud.githubusercontent.com/assets/5222427/11669429/eb054ef8-9dfc-11e5-9be9-26b941c414fb.png">

Loading 1 platforms...
[Nest] Initializing Nest platform...
[Nest] Fetching Nest devices.
[Nest] Away for Nest02AA01AC431402ZH is: false
[Nest] Tempature unit for Nest02AA01AC431402ZH is: Celsius
[Nest] Current temperature for Nest02AA01AC431402ZH is: 20.95
[Nest] Current heating for Nest02AA01AC431402ZH is: 0
[Nest] Current humidity for Nest02AA01AC431402ZH is: 54
[Nest] Target heating for Nest02AA01AC431402ZH is: 1
[Nest] Target temperature for Nest02AA01AC431402ZH is: 16.477
[Nest] Initializing platform accessory 'Nest02AA01AC431402ZH'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ undefined │     
    └────────────┘     
                       
Homebridge is running on port 51826.
[Nest] Update to Device: undefined type: undefined

**Comment by KraigM** [comment]
It shouldn't break anything, it's just logging something that is being ignored. The way nest subscribe works is by making a request that gets the fulfilled as soon as something changes. But if nothing changes it will automatically return with a no changes response so that your connection doesn't time out.

**Comment by KraigM** [comment]
As far as the undefined HomeKit code, that is something to bring up with the main [HomeBridge](https://github.com/nfarina/homebridge) repo

**Comment by KraigM** [comment]
Feel free to comment/reopen if this did not fully answer your question, but I'm going to go ahead and close this. 

Logs cleaned up in release 0.1.1
