### ISSUE TITLE
Siri in Celsius 

### ISSUE THREAD

**Issue by toshibochan** [KraigM/homebridge-nest#66]
My nest is set to Celsius, in the app is showing in Celsius, but when I ask Siri what the temperature she give me only in fahrenheit. Please need help!
Thanks

**Comment by eyv** [comment]
I've had this problem, and found no usable fix except to switch my locale. Northern Mariana Islands does the trick. Everything is the same except the first day of the week is Monday and the temperature is in Celsius. My kind of place :)

**Comment by toshibochan** [comment]
I hope apple have fixi for this! I don't want change my region!

**Comment by KraigM** [comment]
Yeah this one is out of our hands

**Comment by d3bing** [comment]
You can change in regional settings in iOS. No need to change the region, just change the "Temperature Unit" in the same screen.
