### ISSUE TITLE
Nest Cam support 

### ISSUE THREAD

**Issue by leoneleone** [KraigM/homebridge-nest#7]
Can someone please add Nest Cam support to this plugin? 

Maybe it can be added using the HAP-NodeJS HomeKit type - Motion Sensor, since cameras aren't supported just yet. 
It would be great to have the motion detector in the nest cam as a trigger device for HomeKit. 
Also, I'd like to use the Away toggle as well. Currently the plugin won't find and initialize my Nest Cams because it's only looking for Thermostats. 

If my coding skills were up to par I'd do it myself. Hoping someone more knowledgable than me might want to give it a try 😊

**Comment by leoneleone** [comment]
How do i add nest cameras as a device? I am happy for then to just to be considered power switches in HomeKit. I want to have the Away toggle show up in HomeKit so it can be used in HomeKit scenes and can effect my camera on/off settings.

as part of index.js i can see
							// it's a thermostat, adjust this to detect other accessories
							if (data.shared[deviceId].hasOwnProperty('current_temperature')) {

How to I adjust the code to detect Nest Cams? not sure what to use instead of 'current_temperature'

**Comment by KraigM** [comment]
By switches, what do you want On and Off to mean with regards to the camera?  I don't have one of these so Im not sure all of what they can/can't do

**Comment by KraigM** [comment]
I have a prerelease of a new version that switches to the new official NestCloudAPI (#11) which has support for interacting with the NestCamera api's so it should not be difficult to add.

**Comment by leoneleone** [comment]
My use if the word "switches" was confusing. HomeKit does not support cameras yet but I want the Nest Cams to show up as a HomeKit accessory. I thought perhaps if they showed up as on/off switches at least I could them recognised in HomeKit, and then can turn them on and off individually. 

Mainly I want the Away/Home capabilities integrated into HomeKit, like they are now with the Nest Thermostat.

From what I can tell, the Nest Cams have some functions that could work with HomeKit:
1. Motion Detection - it would be great to have the motion data in the camera as a trigger in HomeKit. 
2. Audio Feedback (as per the HAP-NodeJS ServiceTypes.js file). The cameras have two way audio, I'm sure that can be useful somehow.

**Comment by leoneleone** [comment]
According to the Nest API:
"cameras": {
"awJo6rH0IldT2YlIVtYaGQ": {
"device_id": "awJo6rH...",
"software_version": "4.0",
"structure_id": "VqFabWH21nwVyd4RWgJgNb292wa7hG_dUwo2i2SG7j3-BOLY0BA4sw",
"where_id": "d6reb_OZTM...",
"name": "Hallway (upstairs)",
"name_long": "Hallway Camera (upstairs)",
"is_online": true,
"is_streaming": true,
"is_audio_input_enabled": true,
"last_is_online_change": "2015-12-29T18:42:00.000Z",
"is_video_history_enabled": true,
"web_url": "https://home.nest.com/cameras/device_id?auth=access_token",
"app_url": "nestmobile://cameras/device_id?auth=access_token",
"last_event": {
}

I can't seem to find any reference to the Motion Detection functions but I am sure they exist.

**Comment by leoneleone** [comment]
I believe the Nest Cam functions which can be integrated into HomeKit are:
last_event
has_sound
has_motion

is that any help at all?

**Comment by KraigM** [comment]
Added Motion Sensor support and will be in next release (1.1.0)

**Comment by KraigM** [comment]
If anyone can think of anything else that we can add (that Nest exposes) let me know.  I couldn't think of anything else :smile:
