### ISSUE TITLE
Celsius temp display with units=Fahrenheit 

### ISSUE THREAD

**Issue by jdwhite** [KraigM/homebridge-nest#8]
When running the Nest plugin I see this:
```
[Nest] Current temperature for Nest02AA01AB391202M3 is: 21.27  <= Celsuis
[Nest] Target temperature for Nest02AA01AB391202M3 is: 18.968  <= Celsius
[Nest] Tempature unit for Nest02AA01AB391202M3 is: Fahrenheit
[Nest] Away for Nest02AA01AB391202M3 is: false
[Nest] Current humidity for Nest02AA01AB391202M3 is: 45
```

This also appears in the MyTouchHome iOS app:
![img_8572 2](https://cloud.githubusercontent.com/assets/1943283/11727287/a4fac210-9f48-11e5-8557-226649c1c90c.png)

**Comment by KraigM** [comment]
As far as I know, HomeKit deals with temp in Celsius but allows you to display as Fahrenheit. I tried to convert it myself but it assumed those values were Celsius and made them display as over 100.

 I use the Insteon+ app which has a very nice interface for HomeKit. Sometimes it doesn't support certain things, in which case I use the Eve app which does a very good job at supporting all the capabilities of HomeKit, just doesn't work as nice imho

**Comment by KraigM** [comment]
Both of those apps properly display Farenheit no matter if you are viewing or editing

**Comment by jdwhite** [comment]
Confirmed with Eve. Thanks for the insight.
