### ISSUE TITLE
Setting up new API for Nest

### ISSUE THREAD

**Issue by Dazzzz** [KraigM/homebridge-nest#86]
Hi,

I'm attempting to follow your instructions for setting up the Nest to use the New API via their developer site, however when trying to create a product, it is asking for more specific commands in the dialogue box for each permission.
For example, if I tick Thermostat read/write v5, I am then required to enter information such as 
Allows [Product Name] to [take an action] [because/when...]
I do not know what to fill in here and am hoping you can help please.

**Comment by CynanX** [comment]
Hi,

I assumed this was just for descriptive purposes and I just replaced wrote something like, allows nest to change temperature.

--Cynan

**Comment by Dazzzz** [comment]
Hi,

Thanks for getting back to me. I’m not sure what you’re referring to, but my issue is I cannot get HomeBridgeController to work at all. I have successfully got Homebridge working with Nest, but when I add HomeBridgeController and modify the config.json it no longer launches. A few other posters have stated the same error as I receive.

I get this. I’ll include the json file as well.



macminissd:~ sadmin$ homebridge
[10/14/2016, 9:01:18 PM] Loaded plugin: homebridge-controllerlink
[10/14/2016, 9:01:18 PM] Registering platform 'homebridge-controllerlink.HomeBridgeControllerLink'
[10/14/2016, 9:01:18 PM] ---
[10/14/2016, 9:01:18 PM] Loaded plugin: homebridge-nest
[10/14/2016, 9:01:18 PM] Registering platform 'homebridge-nest.Nest'
[10/14/2016, 9:01:18 PM] ---
[10/14/2016, 9:01:18 PM] Loaded config.json with 0 accessories and 2 platforms.
[10/14/2016, 9:01:18 PM] ---
[10/14/2016, 9:01:18 PM] Loading 2 platforms...
[10/14/2016, 9:01:18 PM] Initializing HomeBridgeControllerLink platform...
[10/14/2016, 9:01:18 PM] Initializing Nest platform...
[10/14/2016, 9:01:18 PM] Fetching Nest devices.
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Conf.loadPrefix (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/load-prefix.js:43:14)
    at load_ (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:109:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:96:5)
    at emitOne (events.js:96:13)
    at Conf.emit (events.js:188:7)
    at ConfigChain._resolve (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/config-chain/index.js:281:34)
    at ConfigChain.add (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/config-chain/index.js:259:10)
    at Conf.add (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:341:27)
    at Conf.<anonymous> (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/lib/config/core.js:320:25)
    at ReadFileContext.callback (/usr/local/lib/node_modules/homebridge-controllerlink/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)



{
	"bridge": {
		"name": "Homebridge",
		"username": "18:B4:30:00:34:90",
		"pin": "123-45-678"
	},
	"platforms": [{
		"platform": "HomeBridgeControllerLink",
		"restartStyle": "respawn",
		"disableAutoRestart": false,
		"disableLogger": false
	}, {

		"platform": "Nest",
		"token": "c.5ABsTpo88k5yfNIxZlh...",
		"clientId": "developer client id",
		"clientSecret": "developer client secret.",
		"code": "Pin Code",
		"username": "travisdunaway@mac.com",
		"password": "608upson"
	}]
}









On Oct 15, 2016, at 7:55 AM, CynanX <notifications@github.com> wrote:

Hi,

I assumed this was just for descriptive purposes and I just replaced wrote something like, allows nest to change temperature.

--Cynan

**Comment by CynanX** [comment]
Hi,

I was answering: "For example, if I tick Thermostat read/write v5, I am then required to enter information such as Allows [Product Name] to [take an action] [because/when...]
I do not know what to fill in here and am hoping you can help please"

I've never used HomeBridgeController so can't help there I'm afraid :(

Maybe try putting double quotes around the two 'false' strings.

--Cynan.

**Comment by Dazzzz** [comment]
Hi Cynan,

Sorry for the confusion. The answer is yes. After I tick Thermostat read/write v5 I am required to enter the type of information we both mentioned. I can try some examples, but I’m certainly not sure either and was hoping you’d know what was required.

When I sent this email originally, I addressed it to KraigM who is the author of HomeBridgeController. Do you work with him or am I confused?

Regarding the False Strings, I also tried removing those lines completely form the json file, but the same error occurred. Not sure where it’s trying to resolve a path from.


Cheers

Darren Halprin


📱 +1 (512) 839-7795

✉   darren@halprin.com.au



On Oct 15, 2016, at 8:18 AM, CynanX <notifications@github.com> wrote:

Hi,

I was answering: "For example, if I tick Thermostat read/write v5, I am then required to enter information such as Allows [Product Name] to [take an action] [because/when...]
I do not know what to fill in here and am hoping you can help please"

I've never used HomeBridgeController so can't help there I'm afraid :(

Maybe try putting double quotes around the two 'false' strings.

--Cynan.

**Comment by Dazzzz** [comment]
P.S. I just re-read your earlier response. Perhaps it was just for descriptive purposes, so I’ll try a couple of examples and see how I go. I would prefer to have it using the latest API.

Cheers again.


On Oct 15, 2016, at 2:39 PM, Darren Halprin <darren@halprin.com.au> wrote:

Hi Cynan,

Sorry for the confusion. The answer is yes. After I tick Thermostat read/write v5 I am required to enter the type of information we both mentioned. I can try some examples, but I’m certainly not sure either and was hoping you’d know what was required.

When I sent this email originally, I addressed it to KraigM who is the author of HomeBridgeController. Do you work with him or am I confused?

Regarding the False Strings, I also tried removing those lines completely form the json file, but the same error occurred. Not sure where it’s trying to resolve a path from.


Cheers

Darren Halprin


📱 +1 (512) 839-7795

✉   darren@halprin.com.au <mailto:darren@halprin.com.au>



On Oct 15, 2016, at 8:18 AM, CynanX <notifications@github.com <mailto:notifications@github.com>> wrote:

Hi,

I was answering: "For example, if I tick Thermostat read/write v5, I am then required to enter information such as Allows [Product Name] to [take an action] [because/when...]
I do not know what to fill in here and am hoping you can help please"

I've never used HomeBridgeController so can't help there I'm afraid :(

Maybe try putting double quotes around the two 'false' strings.

--Cynan.

**Comment by toshibochan** [comment]
@Dazzzz never post your email and password on here. Everyone can access your account now! Better change your password!

**Comment by Dazzzz** [comment]
Shit, I just saw that my reply emails were posted here and they never were supposed to be. I have deleted them. I had no idea that that would happen. And also, I realized that in the email I included an email and password, which was also a mistake. I will repost directly here with appropriate information, minus inappropriate information. That is very frustrating.

**Comment by Dazzzz** [comment]
Thanks Cynan,

I didn't realize your reply generated an email to which I replied that then posted here. I assumed it was an email I sent directly to KraigM.

Regarding this original post. I will try something like "allows nest to change temperature" and see how it goes. When I was reading the Nest Developer instructions for those fields, I thought it meant that you were to specify the exact permissions you wanted the API to take advantage of, but I think I mis-interpreted it.

I'll post again when I have tried that and if I succeed in getting it to work with the new API.

**Comment by toshibochan** [comment]
Change your nest account password!!!

**Comment by Dazzzz** [comment]
Will do.

**Comment by Dazzzz** [comment]
I have changed my password. I have also successfully completed this all the way to working with the new API.

Those fields were as Cynan said, just to document the function, so I was able to enter arbitrary information. Thanks for help all.
