### ISSUE TITLE
Away shows up as "N/A" with MyTouchHome app

### ISSUE THREAD

**Issue by jdwhite** [KraigM/homebridge-nest#9]
This may not be related to homebridge-nest, but with the MyTouchHome app the Away toggle is labeled N/A by the app:

![away_is_n_a](https://cloud.githubusercontent.com/assets/1943283/11727373/104c4246-9f49-11e5-95ef-14b15259fb09.png)

**Comment by KraigM** [comment]
That is the new away status. Some apps don't properly handle custom characteristics.

On means away, Off means home.

**Comment by jdwhite** [comment]
Eve app handles this properly.  Sad that MyTouchHome doesn't, plus displaying things in a circular pattern doesn't scale well when you have 30+ accessories.
